name: Thread Workflow

on:
    push:
        branches:
            - main

jobs:
    check-changes:
        runs-on: ubuntu-latest
        outputs:
            client_changed: ${{ steps.client_changed.outputs.client }}
            server_changed: ${{ steps.server_changed.outputs.server }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check for changes in client
              id: client_changed
              uses: dorny/paths-filter@v3
              with: 
                filters: |
                    client:
                        - 'client/**'

            - name: Check for changes in server
              id: server_changed
              uses: dorny/paths-filter@v3
              with: 
                filters: |
                    server:
                        - 'server/**'
    
    client:
        needs: check-changes
        runs-on: ubuntu-latest
        if: needs.check-changes.outputs.client_changed == 'true'
        steps:
            - name: Nice working
              run: echo "Working  on client github actions"
    server:
        needs: check-changes
        runs-on: ubuntu-latest
        if: needs.check-changes-changes.outputs.server_changed == 'true'
        steps:
            - name: Nice working
              run: echo "working on server action"

