name: Thread Workflow

on:
    push:
        branches:
            - main

jobs:
    check-changes:
        runs-on: ubuntu-latest
        outputs:
            client_changed: ${{ steps.client_changed.outputs.client }}
            server_changed: ${{ steps.server_changed.outputs.server }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check for changes in client
              id: client_changed
              uses: dorny/paths-filter@v3
              with: 
                filters: 'client/**'

            - name: Check for changes in server
              id: server_changed
              uses: dorny/paths-filter@v3
              with: 
                filters: 'server/**'
    
    client:
        needs: check-changes
        runs-on: ubuntu-latest
        if: needs.check-changes.output.client_changed == 'true'
        steps:
            - name: Nice working
              run: check 'client has changed'
    server:
        needs: check-changes
        runs-on: ubuntu-latest
        if: needs.check-changes-changes.output.server_changed == 'true'
        steps:
            - name: Nice working
              run: check 'server has changed'

